name: PR Comment

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Add a comment to the PR
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Thank you for your pull request! 🚀
          We will review it shortly.
